# Generated by Django 2.2 on 2019-04-29 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('no_hp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TokoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=20)),
                ('no_telepon', models.IntegerField()),
                ('alamat', models.TextField()),
                ('deskripsi_singkat', models.TextField()),
                ('nama_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.LoginModel')),
            ],
        ),
    ]
