# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_tokomodel_nama_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=200)),
                ('deskripsi_barang', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah_tersedia', models.IntegerField()),
                ('nama_tokos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.TokoModel')),
            ],
        ),
    ]
