# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_barangmodel_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmodel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/'),
        ),
    ]
