# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20190504_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokoBarangModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.BarangModel')),
                ('toko', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.TokoModel')),
            ],
        ),
    ]
