# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_tokobarangmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=20)),
                ('barang', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.BarangModel')),
                ('toko', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.TokoModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='tokobarangmodel',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='tokobarangmodel',
            name='toko',
        ),
        migrations.DeleteModel(
            name='TokoBarangModel',
        ),
    ]
