# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20190505_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmodel',
            name='nama_tokos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
