# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20190505_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmodel',
            name='gambar',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
